name: ci
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v1.2.0
        with:
          version: master
      - name: Build
        run: |
          zig build -Doptimize=Debug
          zig build -Doptimize=ReleaseSafe
